// modelData.js — AI Model definitions for the CDO Boys Chatter System

export const AI_MODELS = [
  {
    id: "gpt-5",
    name: "GPT-5",
    provider: "OpenAI",
    icon: "🏆",
    badge: "premium",
    badgeLabel: "Premium",
    speed: "Medium",
    speedScore: 6,
    creativity: 10,
    accuracy: 10,
    context: "256k",
    cost: "$$$$",
    costLevel: 4,
    bestFor: "Complex reasoning, long-form writing, advanced agentic tasks",
    strengths: [
      "Best-in-class reasoning",
      "Exceptional writing quality",
      "Multi-step task handling",
      "Massive context window",
    ],
    weaknesses: ["Very expensive", "Slower than mini models", "Overkill for simple replies"],
    recommendedFor: ["Premium fan tiers", "High-value conversations", "Complex emotional engagement"],
  },
  {
    id: "gpt-5-mini",
    name: "GPT-5 Mini",
    provider: "OpenAI",
    icon: "⚡",
    badge: "fast",
    badgeLabel: "Fast",
    speed: "Very Fast",
    speedScore: 9,
    creativity: 8,
    accuracy: 8,
    context: "128k",
    cost: "$",
    costLevel: 1,
    bestFor: "Fast replies, high-volume fan messaging, budget operations",
    strengths: [
      "Extremely fast responses",
      "Very low cost",
      "Reliable for short replies",
      "Great throughput",
    ],
    weaknesses: ["Less nuanced than full GPT-5", "Shorter context", "Weaker at complex roleplay"],
    recommendedFor: ["Fast replies", "Large fan volume", "Cheap generation"],
  },
  {
    id: "claude-opus-4",
    name: "Claude Opus 4",
    provider: "Anthropic",
    icon: "🎨",
    badge: "creative",
    badgeLabel: "Creative",
    speed: "Medium",
    speedScore: 5,
    creativity: 10,
    accuracy: 9,
    context: "200k",
    cost: "$$$$",
    costLevel: 4,
    bestFor: "Long-form writing, emotional conversations, premium roleplay",
    strengths: [
      "Most natural conversations",
      "Excellent writing quality",
      "Strong emotional intelligence",
      "Huge context window",
    ],
    weaknesses: ["Slower than Sonnet", "Higher cost", "Can be verbose"],
    recommendedFor: ["High-end conversations", "Emotional engagement", "Premium fans"],
  },
  {
    id: "claude-sonnet-4",
    name: "Claude Sonnet 4",
    provider: "Anthropic",
    icon: "⚖️",
    badge: "balanced",
    badgeLabel: "Balanced",
    speed: "Fast",
    speedScore: 8,
    creativity: 9,
    accuracy: 9,
    context: "200k",
    cost: "$$",
    costLevel: 2,
    bestFor: "Everyday chatter, balanced quality and speed",
    strengths: [
      "Fast and affordable",
      "High quality writing",
      "Great balance of all metrics",
      "Reliable output",
    ],
    weaknesses: ["Not as deep as Opus", "Slightly less creative"],
    recommendedFor: ["Daily chatter workflows", "Mid-tier fan engagement", "Consistent quality"],
  },
  {
    id: "gemini-2-5-pro",
    name: "Gemini 2.5 Pro",
    provider: "Google",
    icon: "🧠",
    badge: "reasoning",
    badgeLabel: "Reasoning",
    speed: "Medium",
    speedScore: 6,
    creativity: 8,
    accuracy: 10,
    context: "1M",
    cost: "$$$",
    costLevel: 3,
    bestFor: "Factual accuracy, massive context tasks, analytical writing",
    strengths: [
      "1M token context — largest available",
      "Top-tier accuracy",
      "Strong reasoning chains",
      "Multimodal capable",
    ],
    weaknesses: ["Less creative personality", "Can sound robotic", "Pricey at scale"],
    recommendedFor: ["Long conversation history", "Detail-oriented fans", "Accuracy-critical replies"],
  },
  {
    id: "gemini-2-5-flash",
    name: "Gemini 2.5 Flash",
    provider: "Google",
    icon: "⚡",
    badge: "fast",
    badgeLabel: "Fast",
    speed: "Very Fast",
    speedScore: 10,
    creativity: 7,
    accuracy: 8,
    context: "1M",
    cost: "$",
    costLevel: 1,
    bestFor: "Bulk generation, fastest possible responses, high-volume ops",
    strengths: [
      "Fastest model available",
      "Incredibly cheap",
      "Still 1M context",
      "Great for automation",
    ],
    weaknesses: ["Less personality than Claude", "Not ideal for premium conversations"],
    recommendedFor: ["Bulk generation", "Fastest responses", "High fan volume"],
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    provider: "DeepSeek",
    icon: "💰",
    badge: "budget",
    badgeLabel: "Budget",
    speed: "Fast",
    speedScore: 7,
    creativity: 8,
    accuracy: 9,
    context: "128k",
    cost: "$",
    costLevel: 1,
    bestFor: "Cost-effective quality generation, bulk tasks",
    strengths: [
      "Extremely cheap",
      "Surprisingly strong writing",
      "Fast inference",
      "Good accuracy",
    ],
    weaknesses: ["Less personality", "Privacy considerations", "Weaker at nuance"],
    recommendedFor: ["Budget operations", "High-volume low-cost", "Testing workflows"],
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek R1",
    provider: "DeepSeek",
    icon: "🧠",
    badge: "reasoning",
    badgeLabel: "Reasoning",
    speed: "Slow",
    speedScore: 3,
    creativity: 7,
    accuracy: 10,
    context: "128k",
    cost: "$$",
    costLevel: 2,
    bestFor: "Complex reasoning, structured replies, logical conversations",
    strengths: [
      "Chain-of-thought reasoning",
      "High accuracy",
      "Good for structured content",
      "Affordable for reasoning",
    ],
    weaknesses: ["Slow due to thinking steps", "Less creative/natural", "Overkill for simple chats"],
    recommendedFor: ["Detailed fan Q&A", "Complex requests", "Structured responses"],
  },
  {
    id: "grok-4",
    name: "Grok 4",
    provider: "xAI",
    icon: "🎨",
    badge: "creative",
    badgeLabel: "Creative",
    speed: "Fast",
    speedScore: 7,
    creativity: 9,
    accuracy: 8,
    context: "128k",
    cost: "$$$",
    costLevel: 3,
    bestFor: "Edgy, witty, personality-rich replies with real-time context",
    strengths: [
      "Unique personality and wit",
      "Real-time web access",
      "Great for playful tones",
      "Handles adult themes well",
    ],
    weaknesses: ["Pricey", "Less widely available", "Can be too sarcastic"],
    recommendedFor: ["Teasing tone conversations", "Witty fan banter", "Personality-driven replies"],
  },
  {
    id: "llama-4-maverick",
    name: "Llama 4 Maverick",
    provider: "Meta",
    icon: "⚡",
    badge: "fast",
    badgeLabel: "Fast",
    speed: "Very Fast",
    speedScore: 9,
    creativity: 8,
    accuracy: 8,
    context: "128k",
    cost: "$",
    costLevel: 1,
    bestFor: "Free/self-hosted generation, fast and capable replies",
    strengths: [
      "Open source — can be free",
      "Fast via Groq",
      "Strong creative writing",
      "Great for local deployment",
    ],
    weaknesses: ["Depends on hosting provider", "Less polished than GPT/Claude"],
    recommendedFor: ["Free tier operations", "Self-hosted setups", "Groq-powered generation"],
  },
  {
    id: "llama-4-scout",
    name: "Llama 4 Scout",
    provider: "Meta",
    icon: "💰",
    badge: "budget",
    badgeLabel: "Budget",
    speed: "Fast",
    speedScore: 8,
    creativity: 7,
    accuracy: 7,
    context: "10M",
    cost: "Free",
    costLevel: 0,
    bestFor: "Ultra-long context tasks, free experimentation",
    strengths: [
      "10M token context window",
      "Essentially free",
      "Great for long chats",
      "Open source",
    ],
    weaknesses: ["Less accurate than frontier models", "Personality not as refined"],
    recommendedFor: ["Very long conversation history", "Free generation", "Experimental use"],
  },
  {
    id: "mistral-large",
    name: "Mistral Large",
    provider: "Mistral",
    icon: "⚖️",
    badge: "balanced",
    badgeLabel: "Balanced",
    speed: "Fast",
    speedScore: 7,
    creativity: 8,
    accuracy: 8,
    context: "128k",
    cost: "$$",
    costLevel: 2,
    bestFor: "European compliance, balanced quality, multilingual",
    strengths: [
      "Strong multilingual support",
      "GDPR-friendly",
      "Good quality/cost balance",
      "Reliable",
    ],
    weaknesses: ["Less creative than Claude", "Smaller ecosystem"],
    recommendedFor: ["Multilingual fans", "Compliance-sensitive ops", "Balanced everyday use"],
  },
  {
    id: "command-r-plus",
    name: "Command R+",
    provider: "Cohere",
    icon: "🧠",
    badge: "reasoning",
    badgeLabel: "Reasoning",
    speed: "Medium",
    speedScore: 6,
    creativity: 7,
    accuracy: 9,
    context: "128k",
    cost: "$$",
    costLevel: 2,
    bestFor: "RAG, enterprise workflows, factual grounded replies",
    strengths: [
      "Excellent for grounded facts",
      "Great RAG performance",
      "Strong instruction following",
      "Good accuracy",
    ],
    weaknesses: ["Less personality", "Not ideal for creative chatter"],
    recommendedFor: ["Fact-based fan questions", "Grounded responses", "Enterprise setups"],
  },
  {
    id: "mixtral-8x22b",
    name: "Mixtral 8x22B",
    provider: "Mistral",
    icon: "💰",
    badge: "budget",
    badgeLabel: "Budget",
    speed: "Fast",
    speedScore: 8,
    creativity: 8,
    accuracy: 8,
    context: "64k",
    cost: "$",
    costLevel: 1,
    bestFor: "Fast, capable, cheap open-source generation",
    strengths: [
      "MoE architecture — efficient",
      "Good quality for price",
      "Open source",
      "Fast inference",
    ],
    weaknesses: ["Shorter context", "Not as polished as frontier models"],
    recommendedFor: ["Budget-conscious teams", "Fast open-source option", "Bulk chatter"],
  },
  {
    id: "qwen-3",
    name: "Qwen 3",
    provider: "Alibaba",
    icon: "🧠",
    badge: "reasoning",
    badgeLabel: "Reasoning",
    speed: "Fast",
    speedScore: 7,
    creativity: 8,
    accuracy: 9,
    context: "128k",
    cost: "$",
    costLevel: 1,
    bestFor: "Asian language fans, affordable frontier-quality reasoning",
    strengths: [
      "Excellent Asian language support",
      "Strong reasoning",
      "Very affordable",
      "Competitive quality",
    ],
    weaknesses: ["Privacy considerations", "Less known in Western markets"],
    recommendedFor: ["Asian fan base", "Multilingual chatter", "Budget reasoning tasks"],
  },
  {
    id: "custom",
    name: "Custom Model",
    provider: "Custom",
    icon: "⚙️",
    badge: "balanced",
    badgeLabel: "Custom",
    speed: "Varies",
    speedScore: 5,
    creativity: 5,
    accuracy: 5,
    context: "Varies",
    cost: "Varies",
    costLevel: 0,
    bestFor: "Your own fine-tuned or self-hosted model",
    strengths: [
      "Fully customizable",
      "Can be fine-tuned for your use case",
      "No rate limits if self-hosted",
    ],
    weaknesses: ["Requires setup", "Performance varies", "You manage infrastructure"],
    recommendedFor: ["Custom fine-tuned models", "Self-hosted setups", "Advanced users"],
  },
];

export const BADGE_STYLES = {
  premium: { background: "rgba(234,179,8,0.15)", color: "#fbbf24", border: "rgba(234,179,8,0.3)" },
  fast: { background: "rgba(34,197,94,0.12)", color: "#4ade80", border: "rgba(34,197,94,0.3)" },
  creative: { background: "rgba(168,85,247,0.12)", color: "#c084fc", border: "rgba(168,85,247,0.3)" },
  balanced: { background: "rgba(59,130,246,0.12)", color: "#60a5fa", border: "rgba(59,130,246,0.3)" },
  reasoning: { background: "rgba(249,115,22,0.12)", color: "#fb923c", border: "rgba(249,115,22,0.3)" },
  budget: { background: "rgba(34,197,94,0.12)", color: "#4ade80", border: "rgba(34,197,94,0.3)" },
};
